#PBS -l walltime=72:0:0
#PBS -l select=1:ncpus=4:mem=4gb
#PBS -N PG_gapseq_batch_missing
#PBS -J 1-24

### script for batch_missing of 99 genomes

# Load modules for any applications

module load anaconda3/personal
source activate gapseq-dev

WORK=$HOME/gapseq
OUT=$HOME/gapseq/output
INPUT=$WORK/batch_files/batch_missing.txt
MEDIA=$WORK/dat/media/LBmed.csv

# JOBID=`echo ${PBS_JOBID} | cut -d'[' -f1`

JOBID=batch_missing

GENOME=`head -n $PBS_ARRAY_INDEX $INPUT | tail -1`
# take the last part of the path as the output folder name
GENOME_NAME=$(basename $GENOME) 

echo "The Genome to analyse for the job ${PBS_ARRAY_INDEX} is ${GENOME_NAME}"
# echo "The temp folder where the output should be saved is ${TMPDIR}"

cd ${OUT}
mkdir ${JOBID}
cd ${JOBID}
mkdir ${GENOME_NAME}
cd ${GENOME_NAME}

# TPDR=${OUT}/${JOBID}

# do the processes
$WORK/gapseq doall $GENOME $MEDIA