#!/usr/bin/env Rscript

## Rscript to plot the genes from pyseer

# libraries
suppressMessages(suppressWarnings(library(optparse)));
suppressMessages(library(tidyverse));
suppressMessages(suppressWarnings(library(ggrepel)));
suppressMessages(suppressWarnings(library(readr)));
suppressMessages(suppressWarnings(library(glue)));
options(warn=-1);
# suppressMessages(library(R.devices));

# option list
option_list = list(
  make_option(c("-i", "--input"), type = "character", default = NULL, 
              help = "gene hits summary from pyseer", metavar = "character"),
  make_option(c("-o", "--output"), type = "character", default = "output.pdf", 
              help = "output filename", metavar = "character")
); 

opt_parser = OptionParser(option_list = option_list);
opt = parse_args(opt_parser);



cat(glue("Reading file {opt$input}... \n"))

gene_hits = read_tsv(opt$input, col_types = cols())


gene_hits %>% 
  # filter(avg_beta > 0.8 | maxp > 7) %>% 
  ggplot(aes(x=avg_beta, y=maxp, colour=avg_maf, size=hits, label=gene)) +
  geom_point(alpha=0.5) +
  geom_text_repel(aes(size=30), 
                  show.legend = FALSE, 
                  colour='black',
                  max.overlaps = Inf) +
  scale_size("Number of \nk-mers", range=c(1,10)) +
  scale_colour_gradient('Average \nMAF') +
  cowplot::theme_cowplot(15) +
  xlab("Average effect size") +
  ylab("Maximum -log10(p-value)")


ggsave(glue("{opt$output}"),
       height = 10, width = 13)

# remove plots generated by default
file.remove("Rplots.pdf")